services:
  - type: web
    name: chronoshift-backend

    runtime: image

    image:
      url: ghcr.io/reneesh28/chronoshift_backend/backend:latest

    plan: free

    envVars:
      - key: MONGODB_URI
        sync: false

      - key: MONGO_DB_NAME
        value: Chronoshift

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: CORS_ALLOWED_ORIGIN
        value: "*"

      - key: AI_REMOTE_ENABLED
        value: "False"

      - key: SIMULATOR_URL
        value: "http://127.0.0.1:8002"

      - key: AI_ENGINE_URL
        value: "http://127.0.0.1:8003"