[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:django]
command=daphne -b 0.0.0.0 -p %(environ_PORT)s core.asgi:application
directory=/app/django_core
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:fastapi]
command=uvicorn main:app --host 127.0.0.1 --port 8002
directory=/app/fastapi_simulator
environment=DJANGO_URL="http://127.0.0.1:%(environ_PORT)s",AI_ENGINE_URL="http://127.0.0.1:8003"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:flask]
command=python main.py
directory=/app/flask_ai_engine
environment=AI_PORT="8003",DJANGO_URL="http://127.0.0.1:%(environ_PORT)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
