# Generated by Django 5.2.14 on 2026-05-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AISummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeline_id", models.CharField(max_length=24)),
                ("branch_id", models.CharField(max_length=24)),
                ("simulation_id", models.CharField(max_length=24)),
                ("risk_score", models.FloatField()),
                ("confidence_score", models.FloatField()),
                ("summary", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_summaries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeline_id",
                    models.CharField(
                        help_text="MongoDB ObjectId of the parent timeline",
                        max_length=24,
                    ),
                ),
                (
                    "parent_branch_id",
                    models.CharField(
                        blank=True,
                        help_text="MongoDB ObjectId of the parent branch",
                        max_length=24,
                        null=True,
                    ),
                ),
                ("branch_name", models.CharField(max_length=255)),
                (
                    "decision_trigger",
                    models.TextField(help_text="Decision that triggered this branch"),
                ),
                ("divergence_score", models.FloatField(default=0.0)),
                ("depth_level", models.IntegerField(default=1)),
                ("status", models.CharField(default="active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "branches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeline_id", models.CharField(max_length=24)),
                ("branch_id", models.CharField(max_length=24)),
                ("event_type", models.CharField(max_length=50)),
                ("event_value", models.TextField()),
                ("created_by", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "events",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeline_id", models.CharField(max_length=24)),
                ("source_branch_id", models.CharField(max_length=24)),
                ("generated_branch_ids", models.JSONField(default=list)),
                (
                    "simulation_status",
                    models.CharField(default="queued", max_length=50),
                ),
                ("divergence_results", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "simulations",
                "managed": False,
            },
        ),
    ]
