# Generated by Django 5.2.14 on 2026-05-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Replay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeline_id", models.CharField(max_length=24)),
                ("branch_id", models.CharField(max_length=24)),
                ("event_sequence", models.JSONField(default=list)),
                ("current_step", models.IntegerField(default=0)),
                ("status", models.CharField(default="playing", max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "replays",
                "managed": False,
            },
        ),
    ]
